# Generated by Django 5.2.8 on 2025-11-15 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ShippinAddress",
            new_name="ShippingAddress",
        ),
    ]
